image: Visual Studio 2013
clone_folder: "c:\\pandoc-crossref"
environment:
  global:
    CABAL_STORE: "C:\\cs"
    CABAL_PACKAGE_DB: "%CABAL_STORE%\\ghc-%GHC_MINOR_VERSION%\\package.db"
    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"
    # see #4201, https://github.com/haskell-tools/haskell-tools/issues/277
    OSARCH: "windows-x86_64"
    GHC_VERSION: "8.4.4"
    GHC_MINOR_VERSION: "8.4.4"
    GHC: "C:\\ProgramData\\chocolatey\\lib\\ghc\\tools\\ghc-%GHC_MINOR_VERSION%\\bin\\ghc.exe"
    CABAL_VERSION: "2.4.1.0"
    CABAL_OPTS: "--constraint pandoc==%PANDOC_VERSION%.* --enable-executable-stripping --enable-split-sections"
    GHC_OPTS: ""
    ARCH: "x64"
    CHOCO_OPTS: ""
  matrix:
  - PANDOC_VERSION: "2.5"

skip_commits:
  files:
    - 'README.md'
    - '.travis.yml'
    - 'linux/*'
    - 'osx/*'

matrix:
  fast_finish: true

cache:
  - '%CABAL_STORE%'

# Note: to reset build cache, do the following in JavaScript
# console on appveyor:
# $.ajax({ url: 'https://ci.appveyor.com/api/projects/jgm/pandoc/buildcache', type: 'DELETE'})

# We don't do a normal C build, but build in test_script
build: off

install:
  - choco install ghc --version %GHC_VERSION% --ignore-dependencies %CHOCO_OPTS%
  - choco install cabal --version %CABAL_VERSION% --ignore-dependencies %CHOCO_OPTS%

# before_test:

test_script:
  - echo %CABAL_OPTS%
  # Note: we manually create cabal store, because of a cabal bug:
  # see https://github.com/haskell/cabal/issues/5516
  - if not exist "%CABAL_PACKAGE_DB%" ( mkdir "%CABAL_PACKAGE_DB%" )
  - cabal --store-dir="%CABAL_STORE%" --version
  - cabal --store-dir="%CABAL_STORE%" new-update
  - cabal --store-dir="%CABAL_STORE%" new-build -w %GHC% %CABAL_OPTS% --ghc-options="%GHC_OPTS%" .
  - forfiles /P .\dist-newstyle /M pandoc-crossref.exe /S /C "cmd /C copy @path C:\pandoc-crossref"

after_test:
  # print built version string
  - .\pandoc-crossref.exe -v
  # create zip artifacts
  - 7z a "%OSARCH%-pandoc_%PANDOC_VERSION%.zip" pandoc-crossref.exe

artifacts:
  - path: '%OSARCH%-pandoc_%PANDOC_VERSION%.zip'
    name: exe

deploy:
  description: 'Description'
  provider: GitHub
  auth_token:
    secure: mYPFGSbgJZ0H2bp6I9vMWvJdgVNUKplWpiPCV3W4sbUwte0jRK56L/8Rts6trCQ7
  artifact: /.*/
  draft: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
