cache:
- 'c:\\sr -> stack.yaml'
- 'c:\\stack\\.stack-work -> stack.yaml'
- 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\stack -> stack.yaml'

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix:
    - STACK_YAML: "stack.yaml"
      PANDOCVER: "21"
      GHCVER: "82"

before_build:
- appveyor DownloadFile http://www.stackage.org/stack/windows-i386 -FileName stack.zip
- 7z x stack.zip stack.exe
- stack setup > nul

build_script:
- echo "" | stack --no-terminal build

after_build:
  - ps: 7z a "windows-ghc$env:GHCVER-pandoc$env:PANDOCVER.zip" "$(.\\stack.exe path --local-install-root)\\bin\\pandoc-crossref.exe"

artifacts:
  - path: windows-ghc$(GHCVER)-pandoc$(PANDOCVER).zip
    name: exe

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
#- echo "" | stack --no-terminal test
# Test disabled for now due to build timing out. Shouldn't be a problem.
- echo "OK"

deploy:
  description: 'Description'
  provider: GitHub
  auth_token:
    secure: mYPFGSbgJZ0H2bp6I9vMWvJdgVNUKplWpiPCV3W4sbUwte0jRK56L/8Rts6trCQ7
  artifact: /.*/
  draft: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
